name: Publish AspNetCore to Nuget.org

on:
  workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '8.x'

    - name: Install dependencies
      run: |
        dotnet restore framework/src/Ddd.Core/Ddd.Core.csproj
        dotnet restore framework/src/AspNetCore/AspNetCore.csproj
        dotnet restore framework/src/AspNetCore.Builder/AspNetCore.Builder.csproj
        dotnet restore framework/src/AspNetCore.Hosting/AspNetCore.Hosting.csproj

    - name: Build
      run: |
        dotnet build framework/src/Ddd.Core/Ddd.Core.csproj --configuration Release --no-restore
        dotnet build framework/src/AspNetCore/AspNetCore.csproj --configuration Release --no-restore
        dotnet build framework/src/AspNetCore.Builder/AspNetCore.Builder.csproj --configuration Release --no-restore
        dotnet build framework/src/AspNetCore.Hosting/AspNetCore.Hosting.csproj --configuration Release --no-restore

    - name: Publish to Nuget.org
      run: |
        rm -rf nuget/

        dotnet pack --no-build framework/src/Ddd.Core/Ddd.Core.csproj --configuration Release --output nuget
        dotnet pack --no-build framework/src/AspNetCore/AspNetCore.csproj --configuration Release --output nuget
        dotnet pack --no-build framework/src/AspNetCore.Builder/AspNetCore.Builder.csproj --configuration Release --output nuget
        dotnet pack --no-build framework/src/AspNetCore.Hosting/AspNetCore.Hosting.csproj --configuration Release --output nuget

        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json
